layout_spectrum: 0.1523435
typography_spectrum: 0.4621598
color:
  saturation: 0.6370446
  lightness: 0.6771865
  brandStrength: 0.874552
  brandColors:
    - '#FEFEFE'
    - '#030203'
    - '#800D02'
    - '#79631E'
    - '#D8CFAB'
  rhythmicContrast: 0.8316504
name: 'Plumbing Tiling Contractors Limited '
