layout_spectrum: 0.1523435
typography_spectrum: 0.4621598
color:
  saturation: 0.6370446
  lightness: 0.6771865
  brandStrength: 0.7214262
  rhythmicContrast: 0.8316504
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
name: 'Plumbing Tiling Contractors Limited '
